language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

branches:
  only:
  - dev
  - master

before_script:
 - set -e
 - cp .env.travis .env
 - travis_retry composer install --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text

cache:
  directories:
  - $HOME/.composer/cache